name: Build Kernel [onclite]

on:
  workflow_dispatch:
    inputs:
      TODO:
        description: What to do?
        default: ''
        type: choice
        options:
          - "kernel"
          - "defconfig"
      KSU:
        description: KernelSU
        default: "Suki"
        type: choice
        options:
          - "None"
          - "Official"
          - "Next"
          - "Suki"
      KSU_SUSFS:
        description: SUSFS for KernelSU
        default: true
        type: boolean
      KSU_MANUAL_HOOK:
        description: KSU Manual Hook
        default: true
        type: boolean

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate Inputs and Secrets
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }} # telegram chat id
          TOKEN: ${{ secrets.TOKEN }} # telegram bot token
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # github token
          KSU: ${{ inputs.KSU }}
          KSU_SUSFS: ${{ inputs.KSU_SUSFS }}
          KSU_MANUAL_HOOK: ${{ inputs.KSU_MANUAL_HOOK }}
        run: |
          ret=0
          _error() {
              echo "❌ ERROR: $*"
              let ret++
          }

          if [[ -z "$CHAT_ID" ]]; then
            _error "Missing CHAT_ID secret (Telegram Chat ID)"
          fi
          if [[ -z "$TOKEN" ]]; then
            _error "Missing TOKEN secret (Telegram Bot Token)"
          fi
          if [[ -z "$GH_TOKEN" ]]; then
            _error "Missing GH_TOKEN secret (GitHub PAT)"
          fi

          if [[ $KSU == "None" && $KSU_SUSFS == "true" ]]; then
              _error "Cannot use SuSFS without KernelSU"
          fi

          if [[ $KSU == "None" && $KSU_MANUAL_HOOK == "true" ]]; then
            _error "Cannot use KSU Manual Hooks without KernelSU!"
          fi

          if [[ $KSU == "Official" && $KSU_MANUAL_HOOK == "true" ]]; then
              _error "KernelSU Official no longer supports manual hook"
          fi

          if [[ $ret -gt 0 ]]; then
            exit $ret
          fi

      - name: Install Dependencies
        run: |
          export MAN_DISABLE=true
          sudo apt update -y
          sudo apt install -y bc cpio flex bison aptitude gh git python-is-python3 \
                              tar perl wget curl lz4 zstd libarchive-tools
          sudo aptitude install -y libssl-dev

      - name: Run Build Script
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }} # telegram chat id
          TOKEN: ${{ secrets.TOKEN }} # telegram bot token
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # github token
          KSU: ${{ inputs.KSU }}
          KSU_SUSFS: ${{ inputs.KSU_SUSFS }}
          KSU_MANUAL_HOOK: ${{ inputs.KSU_MANUAL_HOOK }}
          TODO: ${{ inputs.TODO }}
        run: |
          chmod a+x *.sh
          ./build.sh